apiVersion: v1
kind: ConfigMap
metadata:
  name: osgi-configmap-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"

  # FileInstall Config Files
  game.pid.config: |
    player.initial.lives="$[secret:player_initial_lives;type=long]"
    player.maximum.lives=i"5"
    colors="$[secret:colors;type=String[];delimiter=|;default=green|red|blue]"
